import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "./nextauthprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fred Registration App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="FREDtheme">
      <body className={inter.className}>
        <NextAuthProvider>
        <Navbar />
        {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
