import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "./nextauthprovider";
import StudentProfileTabs from "@/components/StudentProfileTabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fred Registration App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="FREDtheme">
      <body className={`${inter.className} bg-base-200`}>
        <NextAuthProvider>
          <Navbar />
          <div className="flex justify-center h-full">
            <div className="max-w-screen-xl w-full">
              <div className="min-w-full">
              <StudentProfileTabs />
              {children}
            </div>
            </div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
